/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import plus_life.Plus_Life;
import static plus_life.Plus_Life.conferetelalogin;

/**
 *
 * @author Bergson
 */
public class Tela_Configurações extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Configurações
     */
    public Tela_Configurações() throws IOException {
        initComponents();
        
        conferecores();
    }
    
    public void conferecores() throws IOException{
        File file = new File("C:\\PlusLife\\config.pl");
        FileReader freader = new FileReader(file);
        BufferedReader breader = new BufferedReader(freader);
        String corp = breader.readLine();
        String cors = breader.readLine();
        mudacorprincipal(corp);
        mudacorsecundaria(cors);
    }
        
    public void mudacorprincipal(String cor){
        painelcabecalho.setBackground(Color.decode(cor));
        painelrodape.setBackground(Color.decode(cor));
        btnconfirmarrodape.setForeground(Color.decode(cor));
        btncancelarrodape.setForeground(Color.decode(cor));
        txta.setForeground(Color.decode(cor));
        txtb.setForeground(Color.decode(cor));
        txtc.setForeground(Color.decode(cor));
        corprincipal.setText(cor);
    }
    
    public void mudacorsecundaria(String cor){
        painelcabecalho.setForeground(Color.decode(cor));
        painelrodape.setForeground(Color.decode(cor));
        btnconfirmarrodape.setBackground(Color.decode(cor));
        btncancelarrodape.setBackground(Color.decode(cor));
        txtcabecalho.setForeground(Color.decode(cor));
        jPanel2.setBackground(Color.decode(cor));
        corsecundaria.setText(cor);
    }
    
    public void salvarcores(String corprincipal, String corsecundaria){
        
        try{
            File diretorio = new File("C:\\PlusLife");
                diretorio.mkdir();
                
                FileWriter arq = new FileWriter("C:\\PlusLife\\config.pl");
                BufferedWriter writer = new BufferedWriter(arq);
                //writer.newLine();
                writer.write(corprincipal);
                writer.newLine();
                writer.write(corsecundaria);
                writer.flush();
                writer.close();
                JOptionPane.showMessageDialog(null, "Cores salvas!");
        } catch (IOException erro1) {
            
            try {
                File diretorio = new File("C:\\PlusLife");
                diretorio.mkdir();
                
                FileWriter arq = new FileWriter("C:\\PlusLife\\config.pl");
                BufferedWriter writer = new BufferedWriter(arq);
                //writer.newLine();
                writer.write("0");
                writer.flush();
                writer.close();
                salvarcores(corprincipal,corsecundaria);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao criar o diretorio");
                System.out.println(ex);
            }
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corprincipal = new javax.swing.JTextField();
        corsecundaria = new javax.swing.JTextField();
        painelcabecalho = new javax.swing.JPanel();
        txtcabecalho = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txta = new javax.swing.JLabel();
        txtb = new javax.swing.JLabel();
        cp7 = new javax.swing.JButton();
        cp1 = new javax.swing.JButton();
        cp2 = new javax.swing.JButton();
        cp3 = new javax.swing.JButton();
        cp4 = new javax.swing.JButton();
        cp5 = new javax.swing.JButton();
        cp6 = new javax.swing.JButton();
        txtc = new javax.swing.JLabel();
        cs1 = new javax.swing.JButton();
        cs2 = new javax.swing.JButton();
        cs3 = new javax.swing.JButton();
        cs4 = new javax.swing.JButton();
        cs5 = new javax.swing.JButton();
        cs6 = new javax.swing.JButton();
        cs7 = new javax.swing.JButton();
        painelrodape = new javax.swing.JPanel();
        btncancelarrodape = new javax.swing.JButton();
        btnconfirmarrodape = new javax.swing.JButton();

        corprincipal.setText("jTextField1");

        corsecundaria.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelcabecalho.setBackground(new java.awt.Color(102, 153, 255));
        painelcabecalho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcabecalho.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcabecalho.setForeground(new java.awt.Color(255, 255, 255));
        txtcabecalho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtcabecalho.setText("Configurações");
        painelcabecalho.add(txtcabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 320, 50));

        getContentPane().add(painelcabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txta.setForeground(new java.awt.Color(102, 153, 255));
        txta.setText("Cores:");
        jPanel2.add(txta, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, -1, -1));

        txtb.setText("Cor Principal");
        jPanel2.add(txtb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        cp7.setBackground(new java.awt.Color(0, 0, 0));
        cp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp7ActionPerformed(evt);
            }
        });
        jPanel2.add(cp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 60, 50));

        cp1.setBackground(new java.awt.Color(102, 153, 255));
        cp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp1ActionPerformed(evt);
            }
        });
        jPanel2.add(cp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, 50));

        cp2.setBackground(new java.awt.Color(255, 51, 102));
        cp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp2ActionPerformed(evt);
            }
        });
        jPanel2.add(cp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 60, 50));

        cp3.setBackground(new java.awt.Color(255, 255, 0));
        cp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp3ActionPerformed(evt);
            }
        });
        jPanel2.add(cp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 60, 50));

        cp4.setBackground(new java.awt.Color(0, 153, 51));
        cp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp4ActionPerformed(evt);
            }
        });
        jPanel2.add(cp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 60, 50));

        cp5.setBackground(new java.awt.Color(0, 0, 255));
        cp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp5ActionPerformed(evt);
            }
        });
        jPanel2.add(cp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 60, 50));

        cp6.setBackground(new java.awt.Color(255, 255, 255));
        cp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp6ActionPerformed(evt);
            }
        });
        jPanel2.add(cp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 60, 50));

        txtc.setText("Cor Secundária");
        jPanel2.add(txtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        cs1.setBackground(new java.awt.Color(102, 153, 255));
        cs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cs1ActionPerformed(evt);
            }
        });
        jPanel2.add(cs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, 50));

        cs2.setBackground(new java.awt.Color(255, 51, 102));
        cs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cs2ActionPerformed(evt);
            }
        });
        jPanel2.add(cs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, 50));

        cs3.setBackground(new java.awt.Color(255, 255, 0));
        cs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cs3ActionPerformed(evt);
            }
        });
        jPanel2.add(cs3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 60, 50));

        cs4.setBackground(new java.awt.Color(0, 153, 51));
        cs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cs4ActionPerformed(evt);
            }
        });
        jPanel2.add(cs4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 60, 50));

        cs5.setBackground(new java.awt.Color(0, 0, 255));
        cs5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cs5ActionPerformed(evt);
            }
        });
        jPanel2.add(cs5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 60, 50));

        cs6.setBackground(new java.awt.Color(255, 255, 255));
        cs6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cs6ActionPerformed(evt);
            }
        });
        jPanel2.add(cs6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 60, 50));

        cs7.setBackground(new java.awt.Color(0, 0, 0));
        cs7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cs7ActionPerformed(evt);
            }
        });
        jPanel2.add(cs7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 60, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 540, 210));

        painelrodape.setBackground(new java.awt.Color(102, 153, 255));

        btncancelarrodape.setBackground(new java.awt.Color(255, 255, 255));
        btncancelarrodape.setForeground(new java.awt.Color(102, 153, 255));
        btncancelarrodape.setText("Cancelar");
        btncancelarrodape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarrodapeActionPerformed(evt);
            }
        });

        btnconfirmarrodape.setBackground(new java.awt.Color(255, 255, 255));
        btnconfirmarrodape.setForeground(new java.awt.Color(102, 153, 255));
        btnconfirmarrodape.setText("Cofirmar");
        btnconfirmarrodape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarrodapeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelrodapeLayout = new javax.swing.GroupLayout(painelrodape);
        painelrodape.setLayout(painelrodapeLayout);
        painelrodapeLayout.setHorizontalGroup(
            painelrodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelrodapeLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(btnconfirmarrodape, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancelarrodape, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelrodapeLayout.setVerticalGroup(
            painelrodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelrodapeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelrodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelarrodape, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconfirmarrodape, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(painelrodape, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 540, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarrodapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarrodapeActionPerformed
        dispose();
        Plus_Life pl = new Plus_Life();
        pl.conferetelalogin();
    }//GEN-LAST:event_btncancelarrodapeActionPerformed

    private void cp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp1ActionPerformed
        mudacorprincipal("#6699FF");
    }//GEN-LAST:event_cp1ActionPerformed

    private void cp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp2ActionPerformed
        mudacorprincipal("#FF3366");
    }//GEN-LAST:event_cp2ActionPerformed

    private void cp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp3ActionPerformed
        mudacorprincipal("#FFFF00");
    }//GEN-LAST:event_cp3ActionPerformed

    private void cp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp4ActionPerformed
        mudacorprincipal("#009933");
    }//GEN-LAST:event_cp4ActionPerformed

    private void cp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp5ActionPerformed
        mudacorprincipal("#0000FF");
    }//GEN-LAST:event_cp5ActionPerformed

    private void cp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp6ActionPerformed
       mudacorprincipal("#FFFFFF");
    }//GEN-LAST:event_cp6ActionPerformed

    private void cp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp7ActionPerformed
        mudacorprincipal("#000000");
    }//GEN-LAST:event_cp7ActionPerformed

    private void cs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cs1ActionPerformed
        mudacorsecundaria("#6699FF");
    }//GEN-LAST:event_cs1ActionPerformed

    private void cs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cs2ActionPerformed
        mudacorsecundaria("#FF3366");
    }//GEN-LAST:event_cs2ActionPerformed

    private void cs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cs3ActionPerformed
        mudacorsecundaria("#FFFF00");        // TODO add your handling code here:
    }//GEN-LAST:event_cs3ActionPerformed

    private void cs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cs4ActionPerformed
        mudacorsecundaria("#009933");     // TODO add your handling code here:
    }//GEN-LAST:event_cs4ActionPerformed

    private void cs5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cs5ActionPerformed
        mudacorsecundaria("#0000FF");    // TODO add your handling code here:
    }//GEN-LAST:event_cs5ActionPerformed

    private void cs6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cs6ActionPerformed
        mudacorsecundaria("#FFFFFF");      // TODO add your handling code here:
    }//GEN-LAST:event_cs6ActionPerformed

    private void cs7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cs7ActionPerformed
        mudacorsecundaria("#000000");      // TODO add your handling code here:
    }//GEN-LAST:event_cs7ActionPerformed

    private void btnconfirmarrodapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarrodapeActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente salvar essas cores?");
        UIManager.put("OptionPane.yesButtonText", "Sim");
        UIManager.put("OptionPane.noButtonText", "Não");
        if(resposta == 0){
            salvarcores(corprincipal.getText(),corsecundaria.getText());
        }
    }//GEN-LAST:event_btnconfirmarrodapeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Configurações.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_Configurações().setVisible(true);
                    
                } catch (IOException ex) {
                    Logger.getLogger(Tela_Configurações.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelarrodape;
    private javax.swing.JButton btnconfirmarrodape;
    private javax.swing.JTextField corprincipal;
    private javax.swing.JTextField corsecundaria;
    private javax.swing.JButton cp1;
    private javax.swing.JButton cp2;
    private javax.swing.JButton cp3;
    private javax.swing.JButton cp4;
    private javax.swing.JButton cp5;
    private javax.swing.JButton cp6;
    private javax.swing.JButton cp7;
    private javax.swing.JButton cs1;
    private javax.swing.JButton cs2;
    private javax.swing.JButton cs3;
    private javax.swing.JButton cs4;
    private javax.swing.JButton cs5;
    private javax.swing.JButton cs6;
    private javax.swing.JButton cs7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel painelcabecalho;
    private javax.swing.JPanel painelrodape;
    private javax.swing.JLabel txta;
    private javax.swing.JLabel txtb;
    private javax.swing.JLabel txtc;
    private javax.swing.JLabel txtcabecalho;
    // End of variables declaration//GEN-END:variables
}
